//
//  Ingredient.swift
//  RecipeBuilder
//
//  Created by Kristiyan Nachev on 3.01.24.
//

import Foundation

struct Ingredient: Codable, Hashable, Identifiable {
    var id: UUID = UUID()
    var content: IngredientContent = .other
    var measurement: IngredientMeasurement = .pieces
    var value: Int = 0
    
    enum IngredientContent: String, Codable, CaseIterable {
        // Fruits
        case raisin = "Raisins"
        case grape = "Grapes"
        case melon = "Melons"
        case watermelon = "Watermelons"
        case orange = "Oranges"
        case tangerine = "Tangerine"
        case lemon = "Lemons"
        case lime = "Lime"
        case banana = "Bananas"
        case pineapple = "Pineapples"
        case mango = "Mangoes"
        case redApple = "RedApples"
        case greenApple = "GreenApples"
        case pear = "Pears"
        case peach = "Peaches"
        case driedApricots = "DriedApricots"
        case driedFruits = "DriedFruits"
        case cherry = "Cherries"
        case strawberry = "Strawberries"
        case blueberry = "Blueberries"
        case raspberry = "Raspberries"
        case kiwi = "Kiwis"
        case tomato = "Tomatoes"
        case oliveOil = "OliveOil"
        case coconut = "Coconuts"
        case coconutChips = "CoconutChips"
        
        // Vegetables
        case avocado = "Avocados"
        case eggplant = "Eggplants"
        case potato = "Potatoes"
        case carrot = "Carrots"
        case corn = "Corn"
        case hotPepper = "HotPeppers"
        case bellPepper = "BellPeppers"
        case cucumber = "Cucumbers"
        case pickles = "Pickles"
        case zucchini = "Zucchini"
        case spinach = "Spinach"
        case broccoli = "Broccoli"
        case garlic = "Garlic"
        case onion = "Onions"
        case roastedOnions = "RoastedOnions"
        case shives = "Shives"
        case leeks = "Leeks"
        case peanuts = "Peanuts"
        case mushroom = "Mushrooms"
        case ginger = "Ginger"
        case nut = "Nuts"
        case nutmeg = "Nutmeg"
        case hazelnut = "Hazelnuts"
        case walnut = "Walnuts"
        case cashew = "Cashew"
        case almonds = "Almonds"
        case peeledAlmonds = "PeeledAlmonds"
        case filletedAlmonds = "FilletedAlmonds"
        case oatmeal = "Oatmeal"
        case sweetPotato = "SweetPotatoes"
        case pumpkin = "Pumpkins"
        case greenSalad = "GreenSalad"
        case greenPeas = "GreenPeas"
        case greenAsparagus = "GreenAsparagus"
        case beans = "Beans"
        case popcorn = "Popcorn"
        case cannedTomatoes = "CannedTomatoes"
        case tomatoConcentrate = "TomatoConcentrate"
        case hibiscus = "Hibiscus"
        case herb = "Herbs"
        case thyme = "Thyme"
        case dill = "Dill"
        case parsley = "Parsley"
        case savory = "Savory"
        case rosemary = "Rosemary"
        case coriander = "Coriander"
        case cumin = "Cumin"
        case curry = "Curry"
        case garamMasala = "GaramMasala"
        case redPepperPowder = "RedPepperPowder"
        case oregano = "Oregano"
        case mint = "Mint"
        case basil = "Basil"
        case curcuma = "Curcuma"
        case oil = "Oil"
        case vinegar = "Vinegar"
        case flowers = "Flowers"
        case beetroot = "Beetroot"
        case chickpea = "Chickpea"
        case lentils = "Lentils"
        case redLentils = "RedLentils"
        
        // Base products
        case rice = "Rice"
        case flour = "Flour"
        case cheese = "Cheese"
        case emmentaler = "Еmmentaler"
        case scamorza = "Scamorza"
        case parmesan = "Parmesan"
        case cheddar = "Cheddar"
        case blueCheese = "BlueCheese"
        case goatCheese = "GoatCheese"
        case milk = "Milk"
        case yoghurt = "Yoghurt"
        case sourCream = "SourCream"
        case creamCheese = "CreamCheese"
        case cookingCream = "CookingCream"
        case mascarpone = "Mascarpone"
        case ricotta = "Ricotta"
        case mozzarella = "Mozzarella"
        case sweetenedCondensedMilk = "SweetenedCondensedMilk"
        case egg = "Eggs"
        case eggYolks = "EggYolks"
        case butter = "Butter"
        case salt = "Salt"
        case pepper = "Pepper"
        case sugar = "Sugar"
        case brownSugar = "BrownSugar"
        case powderedSugar = "PowderedSugar"
        case bakingPowder = "BakingPowder"
        case bakingSoda = "BakingSoda"
        case brewersYeast = "BrewersYeast"
        case jelly = "Jelly"
        case cinnamon = "Cinnamon"
        case vanilla = "Vanilla"
        case cocoa = "Cocoa"
        case chocolateGlaze = "ChocolateGlaze"
        case other = "Other"
        
        // Meat
        case ham = "Ham"
        case poultryLeg = "PoultryLeg"
        case steak = "Steak"
        case bacon = "Bacon"
        case deer = "Deer"
        case beef = "Beef"
        case boar = "Boar"
        case pork = "Pork"
        case mince = "Mince"
        case rabbit = "Rabbit"
        case kangaroo = "Kangaroo"
        case chicken = "Chicken"
        case turkey = "Turkey"
        case duck = "Duck"
        case frog = "Frog"
        case snail = "Snail"
        
        // Fish & seafood
        case fish = "Fish"
        case tropicalFish = "TropicalFish"
        case blowfish = "Blowfish"
        case shark = "Shark"
        case octopus = "Octopus"
        case crab = "Crab"
        case lobster = "Lobster"
        case shrimp = "Shrimp"
        case squid = "Squid"
        case oyster = "Oyster"
        case prawn = "Prawn"
        
        // Sweets
        case iceCream = "IceCream"
        case cookie = "Cookies"
        case biscotti = "Biscotti"
        case chocolate = "Chocolate"
        case whiteChocolate = "WhiteChocolate"
        case honey = "Honey"
        case appleMousse = "AppleMousse"
        case mapleSyrop = "MapleSyrop"
        case orangePeels = "OrangePeels"
        case freshOrangePeel = "FreshOrangePeel"
        
        // Liquids
        case water = "Water"
        case sparklingWater = "SparklingWater"
        case bouillon = "Bouillon"
        case coffee = "Coffee"
        case tea = "Tea"
        case sake = "Sake"
        case redWine = "RedWine"
        case whiteWine = "WhiteWine"
        case beer = "Beer"
        case champagne = "Champagne"
        case whiskey = "Whiskey"
        case vodka = "Vodka"
        case brandy = "Brandy"
        case bubbleTea = "BubbleTea"
        case juice = "Juice"
        case orangeJuice = "OrangeJuice"
        case tangerineJuice = "TangerineJuice"
        case cactusJuice = "CactusJuice"
        case mate = "Mate"
        
        // Pastries
        case bread = "Bread"
        case breadcrumbs = "Breadcrumbs"
        case croissant = "Croissants"
        case baguette = "Baguettes"
        case flatbread = "Flatbread"
        case pretzel = "Pretzels"
        case bagel = "Bagels"
        case pancakes = "Pancakes"
        case waffle = "Waffles"
        case noodles = "Noodles"
        case pasta = "Pasta"
        case spaetzle = "Spaetzle"
        case lasagneCrust = "LasagneCrust"
        case tacoShells = "TacoShells"
        case mayonnaise = "Mayonnaise"
        case mustard = "Mustard"
        
        var emoji: String {
            switch self {
            case .raisin: return "🍇"
            case .grape: return "🍇"
            case .melon: return "🍈"
            case .watermelon: return "🍉"
            case .orange: return "🍊"
            case .tangerine: return "🍊"
            case .lemon: return "🍋"
            case .lime: return "🍋‍🟩"
            case .banana: return "🍌"
            case .pineapple: return "🍍"
            case .mango: return "🥭"
            case .redApple: return "🍎"
            case .greenApple: return "🍏"
            case .pear: return "🍐"
            case .peach: return "🍑"
            case .driedApricots: return "🍑"
            case .driedFruits: return "🥀"
            case .cherry: return "🍒"
            case .strawberry: return "🍓"
            case .blueberry: return "🫐"
            case .raspberry: return "🩷"
            case .kiwi: return "🥝"
            case .tomato: return "🍅"
            case .oliveOil: return "🫒"
            case .coconut: return "🥥"
            case .coconutChips: return "🥥"
            case .avocado: return "🥑"
            case .eggplant: return "🍆"
            case .potato: return "🥔"
            case .carrot: return "🥕"
            case .corn: return "🌽"
            case .hotPepper: return "🌶️"
            case .bellPepper: return "🫑"
            case .cucumber: return "🥒"
            case .pickles: return "🥒"
            case .zucchini: return "🥒"
            case .spinach: return "🥬"
            case .broccoli: return "🥦"
            case .garlic: return "🧄"
            case .onion: return "🧅"
            case .roastedOnions: return "〽️"
            case .shives: return "🧅🌿"
            case .leeks: return "🌴"
            case .peanuts: return "🥜"
            case .mushroom: return "🍄"
            case .ginger: return "🫚"
            case .nut: return "🌰"
            case .nutmeg: return "🌰"
            case .hazelnut: return "🐿️"
            case .walnut: return "⚜️"
            case .cashew: return "🏷️"
            case .almonds: return "🤎"
            case .peeledAlmonds: return "◻️"
            case .filletedAlmonds: return "❕"
            case .oatmeal: return "⏳"
            case .sweetPotato: return "🍠"
            case .pumpkin: return "🎃"
            case .greenSalad: return "🥗"
            case .greenPeas: return "🫛"
            case .greenAsparagus: return "🫛"
            case .beans: return "🫘"
            case .popcorn: return "🍿"
            case .cannedTomatoes: return "🥫"
            case .tomatoConcentrate: return "🥫"
            case .hibiscus: return "🌺"
            case .herb: return "🌿"
            case .thyme: return "🌿"
            case .dill: return "🌱"
            case .parsley: return "🌿"
            case .savory: return "🍂"
            case .rosemary: return "🍂"
            case .coriander: return "🌿"
            case .cumin: return "🎇"
            case .curry: return "🔸"
            case .garamMasala: return "🟧"
            case .redPepperPowder: return "🌶️"
            case .oregano: return "🍃"
            case .mint: return "🌿"
            case .basil: return "🌱"
            case .curcuma: return "🟧"
            case .oil: return "🌻"
            case .vinegar: return "🍇"
            case .flowers: return "💐"
            case .beetroot: return "🔴"
            case .chickpea: return "🧆"
            case .lentils: return "🟤"
            case .redLentils: return "🟠"
            case .rice: return "🍚"
            case .flour: return "🌾"
            case .cheese: return "🧀"
            case .emmentaler: return "🧀"
            case .scamorza: return "🏷️"
            case .parmesan: return "🧀"
            case .cheddar: return "🟧"
            case .blueCheese: return "🔵"
            case .goatCheese: return "🐐"
            case .milk: return "🥛"
            case .yoghurt: return "🪣"
            case .sourCream: return "🍦"
            case .creamCheese: return "🖱️"
            case .cookingCream: return "🧑‍🍳"
            case .mascarpone: return "💭"
            case .ricotta: return "🥣"
            case .mozzarella: return "⚪"
            case .sweetenedCondensedMilk: return "🍶"
            case .egg: return "🥚"
            case .eggYolks: return "🟡"
            case .butter: return "🧈"
            case .salt: return "🧂"
            case .pepper: return "⚫"
            case .sugar: return "🍬"
            case .brownSugar: return "🧋"
            case .powderedSugar: return "🌨️"
            case .bakingPowder: return "🌋"
            case .bakingSoda: return "🗯️"
            case .jelly: return "🟪"
            case .cinnamon: return "🟫"
            case .vanilla: return "🟡"
            case .cocoa: return "🟤"
            case .chocolateGlaze: return "🪵"
            case .other: return "🥘"
            case .ham: return "🍖"
            case .poultryLeg: return "🍗"
            case .steak: return "🥩"
            case .bacon: return "🥓"
            case .deer: return "🦌"
            case .beef: return "🐂"
            case .boar: return "🐗"
            case .pork: return "🐖"
            case .mince: return "🐖🐂"
            case .rabbit: return "🐇"
            case .kangaroo: return "🦘"
            case .chicken: return "🐔"
            case .turkey: return "🦃"
            case .duck: return "🦆"
            case .frog: return "🐸"
            case .snail: return "🐌"
            case .fish: return "🐟"
            case .tropicalFish: return "🐠"
            case .blowfish: return "🐡"
            case .shark: return "🦈"
            case .octopus: return "🐙"
            case .crab: return "🦀"
            case .lobster: return "🦞"
            case .shrimp: return "🦐"
            case .squid: return "🦑"
            case .oyster: return "🦪"
            case .prawn: return "🍤"
            case .iceCream: return "🍨"
            case .cookie: return "🍪"
            case .biscotti: return "🧽"
            case .chocolate: return "🍫"
            case .whiteChocolate: return "⚪"
            case .honey: return "🍯"
            case .appleMousse: return "🍯"
            case .mapleSyrop: return "🍁"
            case .orangePeels: return "🔸"
            case .freshOrangePeel: return "🍊"
            case .water: return "🚰"
            case .sparklingWater: return "🫧"
            case .bouillon: return "🍲"
            case .brewersYeast: return "🍞"
            case .coffee: return "☕"
            case .tea: return "🫖"
            case .sake: return "🍶"
            case .redWine: return "🍷"
            case .whiteWine: return "🍷🤍"
            case .beer: return "🍺"
            case .champagne: return "🥂"
            case .whiskey: return "🥃"
            case .vodka: return "🫙"
            case .brandy: return "🍹"
            case .bubbleTea: return "🧋"
            case .juice: return "🧃"
            case .orangeJuice: return "🧃"
            case .tangerineJuice: return "🧃"
            case .cactusJuice: return "🌵"
            case .mate: return "🧉"
            case .bread: return "🍞"
            case .breadcrumbs: return "🥖"
            case .croissant: return "🥐"
            case .baguette: return "🥖"
            case .flatbread: return "🫓"
            case .pretzel: return "🥨"
            case .bagel: return "🥯"
            case .pancakes: return "🥞"
            case .waffle: return "🧇"
            case .noodles: return "🍜"
            case .pasta: return "🍝"
            case .spaetzle: return "🥟"
            case .lasagneCrust : return "🥪"
            case .tacoShells: return "🌮"
            case .mayonnaise: return "🗯️"
            case .mustard: return "🌭"
            }
        }
        
        var asReadableString: String {
            String(self.rawValue.reduce("") { (res, a) -> String in
                if a.isUppercase {
                    return res + " \(a)"
                }
                return res + String(a)
            }.dropFirst())
        }
    }

    enum IngredientMeasurement: String, Codable, CaseIterable {
        case pieces = "pcs"
        case slices = "sl"
        case kilograms = "kg"
        case grams = "gr"
        case miligrams = "mg"
        case liters = "l"
        case mililiters = "ml"
        case teaspoons = "tsp"
        case tablespoons = "tbsp"
        case cups = "cups"
    }
    
    private enum CodingKeys : String, CodingKey { case content, measurement, value }
}
